name: Build and Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: install-go
        run: sudo snap install go --classic
      - name: build
        run: go build ./...
      - name: apt-update
        run: sudo apt update
      - name: install-test-dependencies
        run: sudo apt install -y snapd germinate mtools debootstrap fdisk gdisk qemu-system-aarch64 qemu-user-static ubuntu-dev-tools
      - name: test
        run: sudo go test -timeout 0 -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
